### ISSUE TITLE
handlers.json corrupt

### ISSUE THREAD

**Issue by jimmy-1000** [amithm7/webext-open-player#4]
Sadly this code written on handlers.json doesn't work. Firefox take this like corrupt file. Any help ?
"schemes": {
 	"ytdl": {
 		"handlers": [
 			null
 		]
 	}
 }

**Comment by amithm7** [comment]
There should already be a "schemes" key in the file, and few schemes already. The file is a single line by default, so there is a need to format JSON to be readable. Use something like https://jsonlint.com/ to check if the JSON file is valid (also formats it).

You will have to add a comma (`,`) after other schemes and then add this new scheme:

```json
"ytdl": {
	"handlers": [
		null
	]
}
```

**Comment by jimmy-1000** [comment]
> There should already be a "schemes" key in the file, and few schemes already. The file is a single line by default, so there is a need to format JSON to be readable. Use something like https://jsonlint.com/ to check if the JSON file is valid (also formats it).
> 
> You will have to add a comma (`,`) after other schemes and then add this new scheme:
> 
> ```json
> "ytdl": {
> 	"handlers": [
> 		null
> 	]
> }
> ```

Thanks, I will tried.
